// This file was generated by utoipa-ts. Do not edit it manually.

export type Field = "airtable_id" | "ysws" | "country" | "description" | "slack_id" | "github_username" | "display_name" | "code_url" | "demo_url" | "archived_demo" | "archived_repo" | "hours" | "true_hours" | "github_stars" | "approved_at" | "created_at" | "updated_at" | "has_media" | "inferred_repo" | "inferred_username" | "is_github_url";

export type Filter = { field: Field, op: FilterOp, value: JsonValue | null, };

export type FilterOp = "eq" | "neq" | "gt" | "gte" | "lt" | "lte" | "contains" | "not_contains" | "starts_with" | "ends_with" | "is_null" | "is_not_null";

export type FineItem = { id: number, transaction_id: string, amount_cents: number, ysws: string | null, date: string, projects: Array<ProjectSummary>, };

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null;

export type MediaItem = { id: number, project_id: number, airtable_id: string, filename: string | null, mime_type: string, size_bytes: bigint | null, width: number | null, height: number | null, url: string, thumb_small_url: string | null, thumb_small_width: number | null, thumb_small_height: number | null, thumb_large_url: string | null, thumb_large_width: number | null, thumb_large_height: number | null, thumb_full_url: string | null, thumb_full_width: number | null, thumb_full_height: number | null, };

export type MediaSize = "small" | "large" | "full" | "original";

export type ProjectItem = { id: number, airtable_id: string, ysws: string, approved_at: bigint | null, code_url: string | null, country: string | null, demo_url: string | null, description: string | null, slack_id: string | null, github_username: string | null, hours: number | null, true_hours: number | null, has_media: boolean, github_stars: number, display_name: string | null, archived_demo: string | null, archived_repo: string | null, inferred_repo: string | null, inferred_username: string | null, is_github_url: boolean, preview_blurhash: string | null, };

export type ProjectSummary = { id: number, airtable_id: string, ysws: string, approved_at: bigint | null, code_url: string | null, country: string | null, demo_url: string | null, description: string | null, github_username: string | null, hours: number | null, true_hours: number | null, display_name: string | null, archived_demo: string | null, archived_repo: string | null, };

export type QueryRequest = { filters: Array<Filter>, order_by: Field | null, sort_direction: string | null, limit: bigint | null, page: bigint | null, };

export type QueryResults = { data: Array<ProjectItem>, total: bigint, page: bigint, per_page: bigint, };

export type SearchResult = { score: number, id: number, airtable_id: string, ysws: string, approved_at: bigint | null, code_url: string | null, country: string | null, demo_url: string | null, description: string | null, slack_id: string | null, github_username: string | null, hours: number | null, true_hours: number | null, has_media: boolean, github_stars: number, display_name: string | null, archived_demo: string | null, archived_repo: string | null, inferred_repo: string | null, inferred_username: string | null, is_github_url: boolean, preview_blurhash: string | null, };

export type SearchResults = { data: Array<SearchResult>, total: bigint, page: bigint, per_page: bigint, timings: SearchTimings, };

export type SearchTimings = { embeddings_ms: number, query_ms: number, };

export type ServerStatus = { last_refreshed_at: bigint | null, total_projects: bigint | null, };

export type YSWSProgramDetailsResponse = { name: string, total_projects: bigint, total_hours: number, };

export type Api = {
  "GET /fines": {
    responses: {
      200: Array<FineItem>;
    };
  };
  "GET /media/{id}": {
    params: {
      id: string;
    };
    responses: {
      200: Array<MediaItem>;
      404: never;
    };
  };
  "GET /media/{id}/r": {
    params: {
      id: string;
      size?: null | MediaSize;
    };
    responses: {
      303: never;
      404: never;
    };
  };
  "GET /project/{id}": {
    params: {
      id: string;
    };
    responses: {
      200: ProjectItem;
      404: never;
    };
  };
  "GET /recent": {
    responses: {
      200: Array<ProjectItem>;
      404: never;
    };
  };
  "GET /search": {
    params: {
      q: string;
      limit?: number;
      page?: number;
      fts_weight?: number;
      semantic_weight?: number;
      trigram_weight?: number;
      semantic?: boolean;
    };
    responses: {
      200: SearchResults;
      400: never;
    };
  };
  "GET /status": {
    responses: {
      200: ServerStatus;
    };
  };
  "GET /ysws/list": {
    responses: {
      200: Array<string>;
    };
  };
  "GET /ysws/list/details": {
    responses: {
      200: Array<YSWSProgramDetailsResponse>;
    };
  };
  "POST /query": {
    body: QueryRequest;
    responses: {
      200: QueryResults;
      400: never;
    };
  };
};
